### ISSUE TITLE
[InterventionalRadiologyController] error message on totalLenghIsChanging poping up

### ISSUE THREAD

**Issue by epernod** [sofa-framework/BeamAdapter#74]
As soon as the second tool is going out form the first one, error message is poping up:
`msg_error_when(f_printLog.getValue()) << "case 1 should never happen ==> avoid using totalLengthIsChanging !`

and usually lead to a crash in the next steps.

**Comment by damienmarchal** [comment]
Thank for the PR, 
Side note: the use of msg_error with printLog is really bad practice :)
