### ISSUE TITLE
Ninja build subcommand failing

### ISSUE THREAD

**Issue by jaredlawson** [sofa-framework/BeamAdapter#96]
Hello,

I'm running Ubuntu 18.04 with Ninja 1.10.2 and gcc-9 and have successfully built sofa, but I am running into issues building this plugin as an in-tree build.

The following two lines are the only specific indication of which files may be failing:
<FAILED: external_directories/ext_plugin_repo/BeamAdapter/CMakeFiles/BeamAdapter.dir/src/BeamAdapter/component/BeamInterpolation.cpp.o>
<FAILED: external_directories/ext_plugin_repo/BeamAdapter/CMakeFiles/BeamAdapter.dir/src/BeamAdapter/component/WireBeamInterpolation.cpp.o> 

I'm not sure if this is because I'm missing a dependency or my version of Ninja is not compatible.
I didn't see any similar issues on this forum, so I assume it is something simple I have forgotten. Also, the full failure message is much longer, but I can attach if it is useful.

Thanks in advance!

**Comment by fredroy** [comment]
Hello,
I dont think `ninja` itself would be the cause.

What is the version of SOFA you are trying to compile?

**Comment by jaredlawson** [comment]
I am running v22.12. I just cloned and built SOFA yesterday. I am able to run the example demos through runSofa so I'm pretty sure everything else was built correctly.

**Comment by fredroy** [comment]
> I am running v22.12. I just cloned and built SOFA yesterday. I am able to run the example demos through runSofa so I'm pretty sure everything else was built correctly.

Could you post the full error log while compiling BeamAdapter ? The error(s) may be happening before the lines you quoted.
(if it is too big, please use pastebin.com or a similar service)

**Comment by jaredlawson** [comment]
The full terminal log from running ninja is posted here: [pastebin](https://pastebin.com/FiUJzVng)
Thanks for looking into this.

**Comment by fredroy** [comment]
`/home/jared/ext_plugin_repo/BeamAdapter` 
I see that you cloned your own copy of BeamAdapter right ? What branch are you on ?

The error at the compilation time
```
home/jared/ext_plugin_repo/BeamAdapter/src/BeamAdapter/component/BeamInterpolation.inl:104:131: error: no matching function for call to ‘sofa::component::fem::_beaminterpolation_::BeamInterpolation<DataTypes>::initData(sofa::core::objectmodel::Data<sofa::helper::OptionsGroup>*, <brace-enclosed initializer list>, const char [18], const char [97])’
  104 |                                "shape of the cross-section. Can be: circular, elliptic, square, rectangular. Default is circular" ))
      |           
```
is due to a mismatch of versions between SOFA and BeamAdapter.
OptionGroup has been updated in the coming v23.06, so I suppose you are on the master branch of BeamAdapter.
